backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "home"
    label: "Home"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        preview_path: "/"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Message", name: "message", widget: "text" }

  - name: "about"
    label: "About"
    files:
      - label: "About Section"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Bio", name: "bio", widget: "markdown" }
          - { label: "Photo", name: "photo", widget: "image" }

  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    summary: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }


  - name: "contact"
    label: "Contact"
    files:
      - label: "Contact Info"
        name: "contact"
        file: "content/contact.json"
        fields:
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Address", name: "address", widget: "string" }
